// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyibjgqimsjxpmrlvlun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5aWJqZ3FpbXNqeHBtcmx2bHVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MjQ2NTQsImV4cCI6MjA2MTMwMDY1NH0.Tv9FA11tcvnwQX5Qw4veb-bEYmY_QC1JyaLnfmoZQb8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);